name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: keep_hydrated_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --health-start-period=30s

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Generate Prisma Client
      run: yarn prisma generate

    - name: Run database migrations
      run: yarn prisma migrate deploy
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/keep_hydrated_test

    - name: Create test environment file
      run: |
        echo "DATABASE_URL=mysql://root:root@localhost:3306/keep_hydrated_test" > .env.test
        echo "JWT_SECRET=test-secret" >> .env.test
        echo "JWT_EXPIRATION=1d" >> .env.test

    - name: Run tests
      run: yarn test:with-env
      env:
        CI: true
